### PR TITLE
Make the fetch_multi behavior fully match default cache store

### PR DESCRIPTION
**Pull request by marcoadkins**
### Things Done:
- Ensure fetch_multi passes the input name back to the block even if its an object.
- Make the overall behavior of fetch_multi match AR cache fetch_multi

### CODE REVIEW

**Comment by pawurb** [comment]
@marcoadkins thanks for PR. But please rebase to current main, you're also changing unrelated tests.

**Comment by marcoadkins** [comment]
@pawurb Just merged in main. And those unrelated spec updates were to fix an order dependency issue and some typos in the unit tests no behavior change other than ensuring the multi test has a large enough value to compress.

**Comment by pawurb** [comment]
Can you add a test case that will fail with current implementation but is fixed by this PR?

**Comment by marcoadkins** [comment]
@pawurb Done.

**Previous Failure:**
```shell
~/projects/rails-brotli-cache (main*) » bundle exec rspec spec/rails-brotli-cache/store_spec.rb                                                macrobook@Marcos-MBP-2
.........F.............

Failures:

  1) RailsBrotliCache fetch_multi with a complex object that responds to #cache_key works for store and reread
     Failure/Error: big_enough_to_compress_value + key.id

     NoMethodError:
       undefined method `id' for "key_1":String
     # ./spec/rails-brotli-cache/store_spec.rb:126:in `block (5 levels) in <top (required)>'
     # ./lib/rails-brotli-cache/store.rb:118:in `block in fetch_multi'
     # ./lib/rails-brotli-cache/store.rb:115:in `fetch_multi'
     # ./spec/rails-brotli-cache/store_spec.rb:125:in `block (4 levels) in <top (required)>'
     # ./spec/rails-brotli-cache/store_spec.rb:144:in `block (4 levels) in <top (required)>'

Finished in 0.01292 seconds (files took 0.32236 seconds to load)
23 examples, 1 failure

Failed examples:

rspec ./spec/rails-brotli-cache/store_spec.rb:143 # RailsBrotliCache fetch_multi with a complex object that responds to #cache_key works for store and reread
```

**Comment by pawurb** [comment]
Thanks! I've released as 0.6.2

**Pull request merged**
